### ISSUE TITLE
Doesn't work on fedora23

### ISSUE THREAD

**Issue by evolighting** [projecthamster/hamster-shell-extension#108]
I don‘t know why...
It fail to install, and I don't know why.

Or how can I know what cause this?
Where to find the infomation?

**Comment by cebe** [comment]
please describe in more detail what you are doing and what you expect to happen but do not see.

**Comment by evolighting** [comment]
@cebe 
I try to intall it on gnome extension website, I click the toggle botton, there are no error message, but nothing happened. The extension didn't install at all.

Then I try to flow the guide on githud it fail to, it seems the extension have been installed but could not be activated. Still no warning or error message.

I have no idea where to find more infomation about this.

**Comment by cebe** [comment]
This may help you:

http://stackoverflow.com/questions/15608817/how-to-debug-on-gnome-shell-3-6-3-8-or-newer/19867261

**Comment by evolighting** [comment]
@cebe No,I cant find them;
I tried ,but got only "No such file or directory"

on Gnome Version 3.18.2, fedora 23

**Comment by moggers87** [comment]
@evolighting you could try using [LookingGlass](https://wiki.gnome.org/Projects/GnomeShell/LookingGlass)

FWIW, the extension works fine for me on Fedora 23 and Fedora 24 Alpha.

**Comment by evolighting** [comment]
@moggers87 
I guess I would have to learn some basic of gnome extension before I could figure out what is wrong in my case.
I will try later, when I have free time, and I will give feedback as soon as possible.
thanks for your help anyway!

**Comment by LucileQ** [comment]
@moggers87 I had a similar problem.
The hamster shell extension was installed and working on F21. When I upgraded the distribution to F23, the extension was not working, also the extension was marked as outdated and could not be removed via https://extensions.gnome.org/.
I removed the extension with gnome-tweak-tool and could re-install it without problem. Could you try to remove it/install it via gnome tweak tools ?

**Comment by evolighting** [comment]
@LucileQ 
In my case I could never install or re-install it.
And in fact it never work for me...

It is strange as it seems that no one really encounter such a situation.

I lack the basic knowledge about how to debug it, and don't have time to learn it right now, nor at least by summer.

**Comment by oailloud** [comment]
I had the same issue under Fedora 24 but I fixed it by :
- removing gnome extension
- doing a `sudo dnf install hamster-time-tracker`
- reinstalling the extension

**Comment by evolighting** [comment]
![screenshot from 2016-12-01 14-24-10](https://cloud.githubusercontent.com/assets/7067486/20783969/44703968-b7d2-11e6-9509-b3642fb9396a.png)
Sorry for forgetting this issue .
Upgraded to fedora 25, now it installed but look like the pic.
I could not enable it, telling me error loading extension.
How could I get the debug information then?

**Comment by LucileQ** [comment]
@evolighting ,
You can get the error message by running
journalctl -b /usr/bin/gnome-session -f

https://wiki.gnome.org/Projects/GnomeShell/Extensions
I also get an error on F25, which has already been reported on the thread #159.

**Comment by evolighting** [comment]
Update to fedora 26;

And finally it work for me !
