### ISSUE TITLE
Installation from extensions.gnome.org does not work on ubuntu 16.04

### ISSUE THREAD

**Issue by hydrandt** [projecthamster/hamster-shell-extension#114]
Thank you for the great extension!

Unfortunately the installation from extensions.gnome.org does not work. I switch the extension to "ON", dialog comes up asking me if I want to install it, I say yes, and that's it. The folder does not appear in .local/share/gnome-shell/extensions/, nothing happens if I restart gnome shell.

If I can provide some logs, please let me know how to do it.

Manual installation (clone from github, link to the extensions directory, restart shell) works.

**Comment by i2000s** [comment]
No luck for me on Ubuntu 16.04 neither. From `journalctl`, I got the following error with the lasted extension installed:

```
Jul 26 14:04:21 qxd-QC5-Ubuntu org.gnome.Shell.desktop[6570]: (gnome-shell:6570): Gjs-WARNING **: JS ERROR: TypeError:  is null
Jul 26 14:04:21 qxd-QC5-Ubuntu org.gnome.Shell.desktop[6570]: HamsterExtension.prototype._refresh@/home/qxd/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com/extension.js:343
Jul 26 14:04:21 qxd-QC5-Ubuntu org.gnome.Shell.desktop[6570]: _proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:86
Jul 26 14:04:55 qxd-QC5-Ubuntu smbd[10907]: pam_unix(samba:session): session closed for user nobody
```
The error line in extension.js is about `refresh`. Not sure what's wrong there. Any idea?

**Comment by border0464111** [comment]
Hi, I installed` ubuntu 16.04` in virtualbox, installed` gnome-shell-ubuntu-gnome-desktop` and `hamster-applet`. 

Launched `hamster-time-tracker`

Then loaded & activated the widget via `tweaks` everything was fine, I also downloaded `master` and `develop` branch from github, compiled and tested both widget. Still no luck at reproducing the errors you posted. 

Can you provide more information on the installation method you used and the software version you have ?

**Comment by elbenfreund** [comment]
Is this still an issue @hydrandt @i2000s

**Comment by elbenfreund** [comment]
Will close for now, due to a lack of feedback. Please feel more then welcome to reopen if it is still relvant!
