### ISSUE TITLE
Provide unit testing infrastructure

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster-shell-extension#120]
Right now, the entire codebase is absolutly untested. This is a major drawback!
General information on unit testing gnome shell extensions is scarse.
For now, our prefered solutions seems to be
- Unittests with [QUnit](https://qunitjs.com/)
- headless test runs with [phantomjs](http://phantomjs.org/)

We also should look into [gjs-require](https://github.com/topa/gjs-require) for easier CI handling.

Also:
- Add test specific passages to _Get Started_ and _Pull Request Guidelines_ sections in `README.rst`.

**Comment by elbenfreund** [comment]
This looks promissing https://github.com/jonkemp/node-qunit-phantomjs

**Comment by elbenfreund** [comment]
We got a working pipeline up and running. I still struggle integrating/mocking, shell specific magic (``imports.*``, ``String.format``) in a atomic test context however. I am addressing this on SO and #gnome-sell now. Hopefully someone knows something.... :)

**Comment by elbenfreund** [comment]
For reference, a conversation on the matter in #gnome-shell 

> (13:14:59) elbenfreund: ebassi: ty. Btw: is there any documentation on how to write unittests for shell extensions?
> (13:15:13) elbenfreund: I managed to set up a working headless qunit environment that works for the most part
> (13:15:39) elbenfreund: but extensions magic "imports" mechanics do not work in a non-extension context obviously
> (13:16:52) Hussam hat den Raum verlassen (quit: Client exited).
> (13:20:55) ebassi: elbenfreund: Nope. Extensions are executed in the Shell context, so you need the Shell running in order to run them as well.
> (13:21:20) ebassi: Extensions are not sandboxed into their own little world; they literally can rewrite the Shell.
> (13:27:04) elbenfreund: ebassi: so my best bet is to compartmentalize as much as possible and move any non shell dependend code into seperate files that i then can test?
> (13:31:09) Hussam [hussam@185.6.148.66] hat den Raum betreten.
> (13:34:04) razvan hat den Raum verlassen (quit: Ping timeout: 186 seconds).
> (13:38:59) maweki hat den Raum verlassen (quit: Quit: Leaving.).
> (13:50:52) ebassi: elbenfreund: That's one way to do it, yes
> (13:54:08) elbenfreund: ebassi: first of all, thank you very much for the feedback! :) and.. what would be alternatives? Right now I feel a bit at a loss on how to bring basic modern quality assurance to my extension
> (13:55:02) elbenfreund: given that a lot of the "auxilliary code" still uses shell specific functinality like "String.format" I fear not much will be left to move into non dependend files..
> (13:56:25) ebassi: elbenfreund: I'm afraid there are no good answers
> (13:57:04) ebassi: Except that maybe if you think you need to do comprehensive unit testing for your extension then you should consider not writing an extension at all
> (13:57:14) vrishab [vrishab@122.171.206.155] hat den Raum betreten.
> (13:57:32) ebassi: Extensions should be small and possibly self-contained enough not to interact with other extensions
> (13:58:08) ebassi: If it's getting complex enough to warrant unit testing then maybe you should think about writing an application instead
> (13:58:40) ebassi: Unless, obviously, you're interacting with the windowing system

**Comment by border0464111** [comment]
So? what about this one, I also don't feel the need to have a unit testing for this size of projects. Seem like more overhead then actual help IMHO.

**Comment by elbenfreund** [comment]
That seems to be the common consensus it seems :/
Whilst I find this worrying we will just have to live with it I guess.
At lest it is documented here with a somewhat authoritative source.
