### ISSUE TITLE
Usage instructions needed

### ISSUE THREAD

**Issue by a-m-s** [projecthamster/hamster-shell-extension#158]
As demonstrated by #157, the text-box UI is not easily discoverable.

There probably needs to be some words in the Readme or help page, and placeholder text or a tooltip would be better still.

**Comment by Forage** [comment]
Even just the line "Quick categorisation of activities is done by entering your activity in the following format: 'activity@category, description #tag1 #tag2', where the comma is mandatory when adding a description and/or tag(s)" on the GNOME extension page would be a big help already.

**Comment by elbenfreund** [comment]
Closed by PR #235 

Follow up issue: #236
