### ISSUE TITLE
Reevaluate addition of '.idea' to '.gitignore'

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster-shell-extension#163]
PR #160 added ``.idea`` to ``.gitignore``.
Right now it is not really clear why this is needed.

**Comment by border0464111** [comment]
.idea is a folder created by JetBrain products (I use phpStorm) containing project's configurations. 

althrough I understand it's not hamster-shell-extension related.  It's a convenience and a security for me to have it on .gitignore .

**Comment by elbenfreund** [comment]
I see. Wouldn't it be better to have this line as part of your "user .gitignore" e.g. ``~/.gitignore``?

**Comment by border0464111** [comment]
oh, oh yeah.  
I didin't know about --global core.excludesfile 
thx

**Comment by elbenfreund** [comment]
anytime :) feel free to create a PR removing .idea from the project specific ``.gitignore`` :)
