### ISSUE TITLE
"error loading preferences dialogue" on Ubuntu 17.10

### ISSUE THREAD

**Issue by OddBloke** [projecthamster/hamster-shell-extension#211]
```
SyntaxError: redeclaration of let renderer

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43
```

**Comment by elbenfreund** [comment]
Thank you for your  feedback. Would you be so kind to add which version of ``hamster-shell-extension`` throws this error?

**Comment by OddBloke** [comment]
How can I check the version? This was just trying to use it from the extensions store (or whatever it's called) yesterday.

**Comment by elbenfreund** [comment]
Thanks for your getting back to me. You could check the metadata under ``~/.local/share/gnome-shell-extensions/...`` but it sounds like you tried to run the last ``stable`` release.

Do you feel comfortable using basic git commands? In that case you could checkout the current ``develop`` branch which probably fixes this problem. If not, I fear you have to wait a tiny bit longer until it is released properly.

**Comment by OddBloke** [comment]
Hi Eric,

My `metadata.json` looks like this:

```json
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Shell extension for Hamster - the GNOME time tracker. \n\nIMPORTANT: Please file your issues here: 'https://github.com/projecthamster/shell-extension/issues' and not using this sites own 'report issue' functionality!", 
  "extension-id": "project-hamster", 
  "name": "Hamster Time Tracker", 
  "original-authors": [
    "toms.baugis@gmail.com", 
    "jerome@oufella.com", 
    "markus-koller@gmx.ch"
  ], 
  "settings-schema": "org.gnome.shell.extensions.project-hamster", 
  "shell-version": [
    "3.10", 
    "3.12", 
    "3.14", 
    "3.16", 
    "3.18", 
    "3.20"
  ], 
  "url": "https://github.com/projecthamster/shell-extension.git", 
  "uuid": "hamster@projecthamster.wordpress.com", 
  "version": 26
}
```

I'm totally comfortable using git, if you can let me know what to do. :-)


Thanks!

Dan

**Comment by alviser** [comment]
installed from the develop branch and can confirm that the issue is gone and the extension is working, thanks @elbenfreund!

**Comment by elbenfreund** [comment]
@OddBloke 
sorry for the delay. With regards to trying the ``develop`` branch version. [The readme should help you out.](https://github.com/projecthamster/hamster-shell-extension#manual-installation-for-testing-and-development). I am excited to learn if you can confirm @alviser 's impression that the issue is solved there...

**Comment by elbenfreund** [comment]
Will close for now
@OddBloke Did it work? Feel free to reopen if it still persists...

**Comment by gergelypolonkai** [comment]
I still have this on my Fedora box, and extensions.gnome.org doesn’t say there is an update. Is it uploaded there yet?

**Comment by elbenfreund** [comment]
The current development version (`0.10.0`) has not been uploaded to EGO yet. While this version will bring a huge amount of fixes it still has one outstanding issue to be solved before it can be released. You can track its status [here](https://github.com/projecthamster/hamster-shell-extension/projects/2) for example.

If you do not with to wait, you should be able to just checkout the development branch and rund the convenient `make dist` target to build a ready to go version yourself.
