### ISSUE TITLE
Localization is not working

### ISSUE THREAD

**Issue by rhertzog** [projecthamster/hamster-shell-extension#218]
The hamster shell extension has been showing me English strings since I had to upgrade to what's in the develop branch. Yet my environment is configured with a French locale: fr_FR.UTF-8

I do have the required .mo file though as well as the convenience.js file:
```
$ pwd
/home/rhertzog/.local/share/gnome-shell/extensions/contact@projecthamster.org
$ find locale/fr/
locale/fr/
locale/fr/LC_MESSAGES
locale/fr/LC_MESSAGES/hamster-shell-extension.mo
locale/fr/LC_MESSAGES/hamster-shell-extension.po
$ ls
convenience.js  images  metadata.json  schemas   stylesheet.css
extension.js    locale  prefs.js       stuff.js  widgets
$ env|grep LANG
LANG=fr_FR.UTF-8
GDM_LANG=fr_FR.UTF-8
```

I'm running GNOME Shell 3.26.2.

**Comment by elbenfreund** [comment]
While I can confirm the bug, I am somewhat at a loss as to the reasons or how to fix it.

**Comment by rhertzog** [comment]
I don't see anywhere a definition for the "_" function. This is the problem... a merge request will follow soon.
