### ISSUE TITLE
not working in Fedora 18

### ISSUE THREAD

**Issue by jplorier** [projecthamster/hamster-shell-extension#62]
Hi,

Your plugin is exactly what I'm needing but I've installed in both my laptop and my desktop pcs and in neither I can get it to record any activity. I type the activity and hit enter and nothing happens. Is it me?
Regards,

**Comment by border0464111** [comment]
This commit also solve the issue:
https://github.com/pwithnall/hamster-shell-extension/commit/b07954734fea378ad63ee3e9e6ee17e50f528e6e
