### ISSUE TITLE
Task switching from the extensions does not work

### ISSUE THREAD

**Issue by pbuyle** [projecthamster/hamster-shell-extension#70]
Using Gnome Shell 3.4.1 on Ubuntu 12.04.4 (installed from https://launchpad.net/~gnome3-team/+archive/gnome3) with Hamster TimeTracker 2.91.3, I'm unable to switch task from the extensions. Entering the task name in the textfield or clicking on the (>) icon of an already worked on task have no effect. The "Add Ealier Activity" menu item does not work neither.

The extensions is kept in sync. with hamster applet, the current activity is properly displayed and the day's activities are listed. The "Show Overview", "Stop Tracking" and "Tracker Settings" menu items work.

**Comment by border0464111** [comment]
it's a n old issue and I can't reproduce at current state... I fear this issue is stuck here forever .

**Comment by elbenfreund** [comment]
@pbuyle Is this still relevant?

**Comment by elbenfreund** [comment]
Given the lack of feedback, I will close this for now. Please feel free to reopen if it is still relevant.
