### ISSUE TITLE
Appearance settings are broken/inconsistent

### ISSUE THREAD

**Issue by toupeira** [projecthamster/hamster-shell-extension#84]
- "Icon" displays a blank icon
- "Label" displays both the activity name and duration
- "Label and icon" only displays the duration

**Comment by camlafit** [comment]
Hi
 
Icons are too white, and contrast not enough present. Would be nice to evolve this presentation

**Comment by elbenfreund** [comment]
The relevant code seem to live [here](https://github.com/projecthamster/shell-extension/blob/master/extension.js#L451) and is an entire mess altogether. We will deal with this as part of or cleanup.

Thanks for reporting.

**Comment by border0464111** [comment]
Fixed in Pull Request #156 Changes are on the develop branch and will be included in the next release.
